FROM    node:alpine

WORKDIR /app

COPY    ../packages/grpc-server/package.json .
COPY    ../packages/grpc-server/package-lock.json .
COPY    ../packages/grpc-server/rollup.config.mjs .
COPY    ../packages/grpc-server/tsconfig.json .

RUN     npm install
RUN     npm run build

ENTRYPOINT ["node", "dist/index.js"]